import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { generateReport } from '../api/client'
import ReportCard from '../components/ReportCard'
import VoiceButton from '../components/VoiceButton'
import Skeleton from '../components/Skeleton'

const ReportScreen = () => {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const navigate = useNavigate()

  useEffect(() => {
    const playerName = sessionStorage.getItem('playerName')
    const contractValue = parseFloat(sessionStorage.getItem('contractValue'))
    const contractYears = parseInt(sessionStorage.getItem('contractYears'))

    if (!playerName || !contractValue || !contractYears) {
      navigate('/')
      return
    }

    const fetchReport = async () => {
      try {
        setLoading(true)
        const data = await generateReport(playerName, contractValue, contractYears)
        setReport(data.report)
      } catch (error) {
        console.error('Error fetching report:', error)
        alert('Error loading AI report')
      } finally {
        setLoading(false)
      }
    }

    fetchReport()
  }, [navigate])

  const handleBack = () => {
    navigate('/decision')
  }

  const handleNewSearch = () => {
    sessionStorage.clear()
    navigate('/')
  }

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Skeleton className="h-96" />
      </div>
    )
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold mb-2">AI Scouting Report</h1>
          <p className="text-gray-600">
            Comprehensive analysis generated by AI
          </p>
        </div>
        <VoiceButton
          report={report}
          playerName={sessionStorage.getItem('playerName')}
          contractValue={parseFloat(sessionStorage.getItem('contractValue'))}
          contractYears={parseInt(sessionStorage.getItem('contractYears'))}
        />
      </div>

      <div className="mb-6">
        <ReportCard report={report} />
      </div>

      <div className="flex justify-between">
        <button
          onClick={handleBack}
          className="bg-gray-500 text-white px-6 py-3 rounded-lg font-semibold hover:bg-gray-600 transition-colors"
        >
          ← Back
        </button>
        <button
          onClick={handleNewSearch}
          className="bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-colors"
        >
          New Search
        </button>
      </div>
    </div>
  )
}

export default ReportScreen
